// Primary site navigation. Consolidates the legacy site's desktop nav
// (which was the more complete of the two inconsistent legacy menus found
// in the audit) into a cleaner information architecture.

import { services } from './services';

export interface NavLink {
  label: string;
  href: string;
  children?: NavLink[];
}

// Footer service links are derived from the real service records (not
// hand-typed) so hrefs can never drift from the actual /services/[category]/
// [slug] routes generated by src/pages/services/[category]/[service].astro.
function footerServiceLink(slug: string): NavLink {
  const svc = services.find((s) => s.slug === slug);
  if (!svc) throw new Error(`navigation.ts: unknown service slug "${slug}"`);
  return { label: svc.name, href: `/services/${svc.category}/${svc.slug}` };
}

export const mainNav: NavLink[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Services',
    href: '/services',
    children: [
      { label: 'Plumbing', href: '/services/plumbing' },
      { label: 'Sewer & Drain', href: '/services/sewer-drain' },
      { label: 'Heating & HVAC', href: '/services/heating-hvac' },
      { label: 'Air Conditioning', href: '/services/air-conditioning' },
      { label: 'Electrical', href: '/services/electrical' },
      { label: 'Septic', href: '/services/septic' },
    ],
  },
  { label: 'Emergency Plumbing', href: '/emergency-plumbing' },
  { label: 'Service Areas', href: '/service-areas' },
  { label: 'Offers', href: '/offers' },
  { label: 'Financing', href: '/financing' },
  { label: 'Reviews', href: '/reviews' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export const footerNav = {
  services: [
    footerServiceLink('emergency-plumbing'),
    footerServiceLink('drain-cleaning'),
    footerServiceLink('water-heaters'),
    footerServiceLink('sewer-repair'),
    footerServiceLink('furnace-repair'),
    footerServiceLink('electrical-repair'),
  ],
  company: [
    { label: 'About Beacon', href: '/about' },
    { label: 'Careers', href: '/careers' },
    { label: 'Reviews', href: '/reviews' },
    { label: 'Service Areas', href: '/service-areas' },
    { label: 'Financing', href: '/financing' },
    { label: 'Offers', href: '/offers' },
    { label: 'Contact', href: '/contact' },
  ],
  legal: [
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms of Use', href: '/terms-of-use' },
  ],
};
